import { Injectable, Logger, UnauthorizedException, BadRequestException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { initializeApp, getApps, cert, App } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';

/**
 * OTP Verification & Firebase Phone Authentication Service
 *
 * Controlled by OTP_MODE:
 * - 'development' (Current Default): Uses testing OTP 111111 and verifies dev-phone-otp-token.
 * - 'firebase' (Future Mode): Verifies cryptographically signed Firebase Phone Auth ID tokens.
 *
 * TODO: When live Firebase keys are added to environment, set OTP_MODE=firebase.
 */
@Injectable()
export class SuperAdminFirebaseService {
  private readonly logger = new Logger(SuperAdminFirebaseService.name);
  private firebaseApp: App | null = null;
  private isConfigured = false;
  private readonly otpMode: string;

  constructor(private readonly config: ConfigService) {
    this.otpMode = (this.config.get<string>('OTP_MODE') || 'development').toLowerCase();
    this.initFirebase();
  }

  private initFirebase() {
    const projectId = this.config.get<string>('FIREBASE_PROJECT_ID');
    const clientEmail = this.config.get<string>('FIREBASE_CLIENT_EMAIL');
    const privateKeyRaw = this.config.get<string>('FIREBASE_PRIVATE_KEY');
    const privateKey = privateKeyRaw ? privateKeyRaw.replace(/\\n/g, '\n') : undefined;

    try {
      if (projectId && clientEmail && privateKey) {
        const apps = getApps();
        this.firebaseApp =
          apps.length > 0
            ? apps[0]
            : initializeApp({
                credential: cert({
                  projectId,
                  clientEmail,
                  privateKey,
                }),
              });
        this.isConfigured = true;
        this.logger.log(`✅ Firebase Admin initialized with service account for project: ${projectId}`);
      } else if (projectId) {
        const apps = getApps();
        this.firebaseApp =
          apps.length > 0
            ? apps[0]
            : initializeApp({
                projectId,
              });
        this.isConfigured = true;
        this.logger.log(`✅ Firebase Admin initialized with Project ID: ${projectId}`);
      } else {
        this.logger.log(
          `ℹ️ OTP_MODE is set to "${this.otpMode}". Testing OTP mode active (OTP: 111111).`,
        );
      }
    } catch (err: any) {
      this.logger.error(`Failed to initialize Firebase Admin SDK: ${err.message}`);
    }
  }

  /**
   * Verifies Phone Verification Token and asserts it matches the partner contact phone.
   * Prevents API bypass by rejecting missing, malformed, or mismatched tokens.
   */
  async verifyPhoneToken(
    idToken: string,
    expectedPhone: string,
  ): Promise<{ uid: string; phoneNumber?: string }> {
    if (!idToken || typeof idToken !== 'string' || !idToken.trim()) {
      throw new BadRequestException('Phone Verification Token (firebaseIdToken) is required to provision a partner.');
    }

    if (!expectedPhone || typeof expectedPhone !== 'string' || !expectedPhone.trim()) {
      throw new BadRequestException('Contact Phone number is required for verification.');
    }

    const cleanExpected = expectedPhone.replace(/[\s\-\(\)]/g, '');
    const normExpected = cleanExpected.startsWith('+') ? cleanExpected : `+91${cleanExpected}`;

    // Mode 1: Development Testing Mode (Controlled via OTP_MODE=development)
    if (this.otpMode === 'development' || !this.isConfigured) {
      // Must be a verified test token generated by confirming 111111
      if (!idToken.startsWith('dev-phone-otp-token:')) {
        throw new UnauthorizedException(
          'Invalid phone verification token. Phone verification must be completed before provisioning.',
        );
      }

      const parts = idToken.split(':');
      // Format: dev-phone-otp-token:<phone>:<timestamp>:<nonce>
      const tokenPhone = parts[1] || '';
      const cleanTokenPhone = tokenPhone.replace(/[\s\-\(\)]/g, '');

      const match =
        cleanTokenPhone === cleanExpected ||
        cleanTokenPhone === normExpected ||
        (cleanExpected.length >= 10 && cleanTokenPhone.endsWith(cleanExpected.slice(-10)));

      if (!match) {
        throw new BadRequestException(
          `Verified phone number does not match administrator contact phone (${cleanExpected}).`,
        );
      }

      return { uid: `dev-user-${cleanExpected}`, phoneNumber: cleanExpected };
    }

    // Mode 2: Real Firebase Phone Authentication (Active when OTP_MODE=firebase)
    // TODO: Production Firebase Phone Auth verification
    if (this.isConfigured && this.firebaseApp) {
      try {
        const auth = getAuth(this.firebaseApp);
        const decoded = await auth.verifyIdToken(idToken.trim());
        const verifiedPhone = (decoded.phone_number || '').replace(/[\s\-\(\)]/g, '');

        if (!verifiedPhone) {
          throw new UnauthorizedException('Token is not a verified phone authentication token.');
        }

        const match =
          verifiedPhone === cleanExpected ||
          verifiedPhone === normExpected ||
          (cleanExpected.length >= 10 && verifiedPhone.endsWith(cleanExpected.slice(-10)));

        if (!match) {
          throw new BadRequestException(
            `Verified phone number (${verifiedPhone}) does not match administrator phone (${cleanExpected}).`,
          );
        }

        return { uid: decoded.uid, phoneNumber: decoded.phone_number };
      } catch (err: any) {
        if (err instanceof BadRequestException || err instanceof UnauthorizedException) {
          throw err;
        }
        if (err.code === 'auth/id-token-expired') {
          throw new UnauthorizedException('The verification token has expired. Please verify your phone number again.');
        }
        throw new UnauthorizedException(`Firebase token verification failed: ${err.message || 'Invalid token'}`);
      }
    }

    throw new UnauthorizedException('Phone verification service is not properly configured.');
  }
}
