"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, Copy, Globe, Loader2, Palette, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { api } from "@/lib/api/axios";

const cleanDomain = (value: string) => value.toLowerCase().trim().replace(/^https?:\/\//, "").replace(/\/.*$/, "").replace(/:\d+$/, "").replace(/\s+/g, "");

export default function BrandSettingsPage() {
  const [brandName, setBrandName] = useState(""); const [primaryColor, setPrimaryColor] = useState("#0f172a");
  const [logoUrl, setLogoUrl] = useState(""); const [faviconUrl, setFaviconUrl] = useState(""); const [domain, setDomain] = useState("");
  const [mapping, setMapping] = useState<any>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [verifying, setVerifying] = useState(false);
  const [notice, setNotice] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const status = mapping?.status || "UNCONFIGURED"; const normalizedDomain = useMemo(() => cleanDomain(domain), [domain]); const host = normalizedDomain.split(".").length > 2 ? normalizedDomain.split(".")[0] : "@";

  const load = async () => { setLoading(true); try { const res = await api.get("/partner/brand-settings"); const data = res.data?.data || res.data; setBrandName(data.brandName || ""); setPrimaryColor(data.primaryColor || "#0f172a"); setLogoUrl(data.logoUrl || ""); setFaviconUrl(data.faviconUrl || ""); setMapping(data.domainMapping || null); setDomain(data.domainMapping?.domain || ""); } catch (error: any) { setNotice({ type: "error", text: error.response?.data?.message || "Unable to load brand settings." }); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setNotice(null); try { const res = await api.put("/partner/brand-settings", { brandName, primaryColor, logoUrl, faviconUrl, domain: normalizedDomain || undefined }); const data = res.data?.data || res.data; setMapping(data.domainMapping || null); setDomain(data.domainMapping?.domain || normalizedDomain); setNotice({ type: "success", text: "Brand settings saved. Configure DNS, then verify the record." }); } catch (error: any) { setNotice({ type: "error", text: error.response?.data?.message || "Unable to save brand settings." }); } finally { setSaving(false); } };
  const verify = async () => { setVerifying(true); setNotice(null); try { const res = await api.post("/partner/brand-settings/verify-domain"); const data = res.data?.data || res.data; setMapping((previous: any) => previous ? { ...previous, status: data.status, sslStatus: data.sslStatus, verifiedAt: data.verifiedAt, lastCheckedAt: new Date().toISOString() } : previous); setNotice({ type: data.success ? "success" : "error", text: data.message || (data.success ? "Domain successfully verified and activated!" : "CNAME record not found or still propagating.") }); } catch (error: any) { setNotice({ type: "error", text: error.response?.data?.message || "DNS verification failed." }); } finally { setVerifying(false); } };
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); setNotice({ type: "success", text: "Copied to clipboard." }); };
  const statusClass = status === "VERIFIED" ? "bg-emerald-100 text-emerald-800" : status === "PENDING" ? "bg-amber-100 text-amber-800" : "bg-rose-100 text-rose-800";
  const statusLabel = status === "VERIFIED" ? "Verified & Active" : status === "PENDING" ? "Pending DNS Propagation" : status === "FAILED" ? "Action Required / Failed" : "Unconfigured";

  if (loading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin" /></div>;
  return <form onSubmit={save} className="mx-auto max-w-5xl space-y-6">
    <div className="flex flex-col gap-3 border-b pb-5 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-extrabold"><Palette className="h-6 w-6 text-primary" />Brand Settings</h1><p className="mt-1 text-sm text-muted-foreground">Configure your white-label portal and custom domain.</p></div><Button disabled={saving}>{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}Save Brand Settings</Button></div>
    {notice && <div className={`flex gap-2 rounded-xl border p-3 text-sm ${notice.type === "success" ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-rose-300 bg-rose-50 text-rose-800"}`}>{notice.type === "success" ? <CheckCircle2 className="h-4 w-4 shrink-0" /> : <AlertCircle className="h-4 w-4 shrink-0" />}{notice.text}</div>}
    <div className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2">
      <section className="space-y-4 rounded-2xl border bg-card p-5"><h2 className="font-bold">Brand Assets</h2><label className="block text-sm">Brand name<Input className="mt-1" value={brandName} onChange={(e) => setBrandName(e.target.value)} /></label><label className="block text-sm">Primary color<Input className="mt-1" value={primaryColor} onChange={(e) => setPrimaryColor(e.target.value)} /></label><label className="block text-sm">Brand Logo URL<Input className="mt-1" value={logoUrl} onChange={(e) => setLogoUrl(e.target.value)} placeholder="https://agency.com/logo.svg" /></label><label className="block text-sm">Favicon URL<Input className="mt-1" value={faviconUrl} onChange={(e) => setFaviconUrl(e.target.value)} placeholder="https://agency.com/favicon.ico" /></label></section>
      <section className="space-y-4 rounded-2xl border bg-card p-5"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-bold"><Globe className="h-4 w-4" />Custom Domain & DNS</h2><Badge className={statusClass}>{statusLabel}</Badge></div><label className="block text-sm">Custom Domain Hostname<Input className="mt-1 font-mono" value={domain} onChange={(e) => setDomain(e.target.value)} onBlur={() => setDomain(normalizedDomain)} placeholder="portal.agency.com" /></label><div className="rounded-xl border bg-muted/30 p-4 text-sm"><p className="font-semibold">Create this DNS record</p><p className="mt-1 text-xs text-muted-foreground">DNS propagation can take up to 24 hours.</p><div className="mt-3 grid gap-2 font-mono text-xs"><div className="flex justify-between rounded bg-background p-2">Record <span>CNAME</span></div><div className="flex justify-between rounded bg-background p-2">Host <button type="button" onClick={() => copy(host)} className="flex items-center gap-1 underline">{host}<Copy className="h-3 w-3" /></button></div><div className="flex justify-between rounded bg-background p-2">Target <button type="button" onClick={() => copy("cname.appnix.co.in")} className="flex items-center gap-1 underline">cname.appnix.co.in<Copy className="h-3 w-3" /></button></div></div></div><Button type="button" variant="outline" onClick={verify} disabled={!normalizedDomain || !mapping || verifying}>{verifying && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Verify DNS Record</Button></section>
    </div><aside className="h-fit rounded-2xl border bg-card p-5 lg:sticky lg:top-20"><p className="font-bold">Live Preview</p><div className="mt-4 overflow-hidden rounded-xl border"><div className="flex h-14 items-center gap-2 px-3" style={{ borderTop: `4px solid ${primaryColor}` }}>{logoUrl ? <img src={logoUrl} alt="Brand logo preview" className="h-8 max-w-28 object-contain" /> : <span className="grid h-8 w-8 place-items-center rounded text-xs font-bold text-white" style={{ backgroundColor: primaryColor }}>{brandName.slice(0, 2).toUpperCase() || "WL"}</span>}<strong>{brandName || "Your Brand"}</strong></div><div className="p-4 text-xs text-muted-foreground">Client Portal<br /><strong className="text-foreground">Welcome back</strong></div></div></aside></div>
  </form>;
}
